// <auto-generated />
using System;
using MVC_Projec2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Projec2.Migrations
{
    [DbContext(typeof(MVCProjectContext))]
    [Migration("20250411232928_up4")]
    partial class up4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_Projec2.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "915f09d1-f412-4330-b6cf-858d7657b54d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9e9bffd-7450-472c-8e4f-92e4d980c58c",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBO55+ph9vjwtkScwr6pNUoN3V1nz9NgHz8AjLLl5paYFD0z8yhxQI0O29DEUZMmhw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "daa6ca08-8ebf-4f80-b76b-85e227f74f96",
                            TwoFactorEnabled = false,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = "20825a0f-7b3e-46b6-8880-271eac074c8e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "665b2367-d37f-4e80-aba8-49d141785c60",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJCTJmoikiDCYpl0VblLis7fYN7g1rz+d+mfwCslDWZOJpVbmjkmumL0jr67d/TPZQ==",
                            PhoneNumber = "9876543210",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ae7ddc9a-11f4-4013-913c-f85dd91f0b89",
                            TwoFactorEnabled = false,
                            UserName = "user@example.com"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Atelier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("priceRange")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Ateliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Downtown",
                            Name = "Elite Atelier",
                            priceRange = 5000.0
                        },
                        new
                        {
                            Id = 2,
                            Location = "Uptown",
                            Name = "Royal Designs",
                            priceRange = 3000.0
                        },
                        new
                        {
                            Id = 3,
                            Location = "City Center",
                            Name = "Glamorous Styles",
                            priceRange = 5000.0
                        },
                        new
                        {
                            Id = 4,
                            Location = "Suburb",
                            Name = "Elegant Creations",
                            priceRange = 3000.0
                        },
                        new
                        {
                            Id = 5,
                            Location = "North Park",
                            Name = "Chic Styles",
                            priceRange = 1500.0
                        },
                        new
                        {
                            Id = 6,
                            Location = "South Side",
                            Name = "Vintage Touch",
                            priceRange = 2500.0
                        },
                        new
                        {
                            Id = 7,
                            Location = "Midtown",
                            Name = "Modern Artistry",
                            priceRange = 5000.0
                        },
                        new
                        {
                            Id = 8,
                            Location = "East End",
                            Name = "Exquisite Design",
                            priceRange = 2500.0
                        },
                        new
                        {
                            Id = 9,
                            Location = "West End",
                            Name = "Timeless Beauty",
                            priceRange = 5000.0
                        },
                        new
                        {
                            Id = 10,
                            Location = "Central Square",
                            Name = "Fashion Forward",
                            priceRange = 1500.0
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.AtelierImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtelierId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtelierId");

                    b.ToTable("AtelierImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtelierId = 1,
                            ImageUrl = "atelier1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AtelierId = 2,
                            ImageUrl = "atelier2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AtelierId = 3,
                            ImageUrl = "atelier3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AtelierId = 4,
                            ImageUrl = "atelier4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            AtelierId = 5,
                            ImageUrl = "atelier5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            AtelierId = 6,
                            ImageUrl = "atelier6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            AtelierId = 7,
                            ImageUrl = "atelier7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            AtelierId = 8,
                            ImageUrl = "atelier8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            AtelierId = 9,
                            ImageUrl = "atelier9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            AtelierId = 10,
                            ImageUrl = "atelier10.jpg"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Atelier_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Decor_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Hall_Id")
                        .HasColumnType("int");

                    b.Property<int?>("MakeupId")
                        .HasColumnType("int");

                    b.Property<int?>("Session_Id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Atelier_Id");

                    b.HasIndex("Decor_Id");

                    b.HasIndex("Hall_Id");

                    b.HasIndex("MakeupId");

                    b.HasIndex("Session_Id");

                    b.HasIndex("user_id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Atelier_Id = 3,
                            Created_at = new DateTime(2025, 4, 12, 1, 29, 26, 646, DateTimeKind.Local).AddTicks(1493),
                            Decor_Id = 1,
                            Hall_Id = 2,
                            MakeupId = 1,
                            Session_Id = 2,
                            Status = "Confirmed",
                            user_id = "915f09d1-f412-4330-b6cf-858d7657b54d"
                        },
                        new
                        {
                            Id = 2,
                            Atelier_Id = 1,
                            Created_at = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Decor_Id = 2,
                            Hall_Id = 1,
                            MakeupId = 4,
                            Session_Id = 1,
                            Status = "Pending",
                            user_id = "915f09d1-f412-4330-b6cf-858d7657b54d"
                        },
                        new
                        {
                            Id = 3,
                            Atelier_Id = 3,
                            Created_at = new DateTime(2025, 4, 12, 1, 29, 26, 646, DateTimeKind.Local).AddTicks(1642),
                            Decor_Id = 1,
                            Hall_Id = 2,
                            MakeupId = 1,
                            Session_Id = 2,
                            Status = "Confirmed",
                            user_id = "915f09d1-f412-4330-b6cf-858d7657b54d"
                        },
                        new
                        {
                            Id = 4,
                            Atelier_Id = 1,
                            Created_at = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            Decor_Id = 2,
                            Hall_Id = 1,
                            MakeupId = 4,
                            Session_Id = 1,
                            Status = "Pending",
                            user_id = "915f09d1-f412-4330-b6cf-858d7657b54d"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Excellent service!",
                            CreatedAt = new DateTime(2025, 4, 12, 1, 29, 26, 646, DateTimeKind.Local).AddTicks(1703),
                            ServiceId = 0,
                            ServiceType = 0,
                            UserId = "915f09d1-f412-4330-b6cf-858d7657b54d"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Decor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Decors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Timeless decor with elegant and traditional designs, perfect for a sophisticated atmosphere.",
                            Price = 5000,
                            Style = "Classic"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sleek and contemporary design with clean lines and minimalistic features.",
                            Price = 7000,
                            Style = "Modern"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Natural and earthy designs featuring wood, stone, and vintage elements for a cozy feel.",
                            Price = 4500,
                            Style = "Rustic"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Retro-inspired decor with nostalgic and old-world charm, ideal for classic settings.",
                            Price = 5500,
                            Style = "Vintage"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Rough and raw designs with exposed metals, bricks, and unfinished elements.",
                            Price = 6000,
                            Style = "Industrial"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bohemian style with vibrant colors, eclectic patterns, and artistic, free-spirited elements.",
                            Price = 4000,
                            Style = "Boho"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Simplicity at its finest, focusing on clean spaces and functional, uncluttered designs.",
                            Price = 6500,
                            Style = "Minimalist"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Luxurious and glamorous style featuring bold geometric patterns and rich colors.",
                            Price = 7000,
                            Style = "Art Deco"
                        },
                        new
                        {
                            Id = 9,
                            Description = "High-end and dazzling decor with rich textures, metallic accents, and sophisticated lighting.",
                            Price = 8000,
                            Style = "Glam"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A charming, weathered look with soft pastel colors, distressed furniture, and vintage accessories.",
                            Price = 4500,
                            Style = "Shabby Chic"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.DecoreImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DecorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DecorId");

                    b.ToTable("DecoreImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DecorId = 1,
                            ImageUrl = "decor1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            DecorId = 2,
                            ImageUrl = "decor2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            DecorId = 3,
                            ImageUrl = "decor3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            DecorId = 4,
                            ImageUrl = "decor4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            DecorId = 5,
                            ImageUrl = "decor5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            DecorId = 6,
                            ImageUrl = "decor6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            DecorId = 7,
                            ImageUrl = "decor7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            DecorId = 8,
                            ImageUrl = "decor8.jpg"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500,
                            Location = "Cairo",
                            Name = "Grand Hall",
                            Price = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 300,
                            Location = "Alexandria",
                            Name = "Crystal Ballroom",
                            Price = 8000.0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 200,
                            Location = "Sharm El Sheikh",
                            Name = "Sunset Venue",
                            Price = 5000.0
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 400,
                            Location = "Giza",
                            Name = "Majestic Hall",
                            Price = 9000.0
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 350,
                            Location = "Hurghada",
                            Name = "Ocean View",
                            Price = 7500.0
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 600,
                            Location = "New Cairo",
                            Name = "Skyline Pavilion",
                            Price = 12000.0
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 250,
                            Location = "Tanta",
                            Name = "Moonlight Hall",
                            Price = 6000.0
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 450,
                            Location = "Mansoura",
                            Name = "Royal Suite",
                            Price = 11000.0
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 500,
                            Location = "Port Said",
                            Name = "Elite Venue",
                            Price = 10500.0
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 700,
                            Location = "Luxor",
                            Name = "Luxury Retreat",
                            Price = 15000.0
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.HallImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.ToTable("HallImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HallId = 1,
                            ImageUrl = "hall1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            HallId = 2,
                            ImageUrl = "hall2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            HallId = 3,
                            ImageUrl = "hall3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            HallId = 4,
                            ImageUrl = "hall4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            HallId = 5,
                            ImageUrl = "hall5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            HallId = 6,
                            ImageUrl = "hall6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            HallId = 7,
                            ImageUrl = "hall7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            HallId = 8,
                            ImageUrl = "hall8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            HallId = 9,
                            ImageUrl = "hall9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            HallId = 10,
                            ImageUrl = "hall10.jpg"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.MakeUpImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MakeUpId");

                    b.ToTable("MakeUpImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "makeUp1.jpg",
                            MakeUpId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "makeUp2.jpg",
                            MakeUpId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "makeUp3.jpg",
                            MakeUpId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "makeUp4.jpg",
                            MakeUpId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "makeUp5.jpg",
                            MakeUpId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "makeUp6.jpg",
                            MakeUpId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "makeUp7.jpg",
                            MakeUpId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "makeUp8.jpg",
                            MakeUpId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "makeUp9.jpg",
                            MakeUpId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "makeUp10.jpg",
                            MakeUpId = 10
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.MakeUp_Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MakeUpServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Flawless makeup designed to enhance the bride's natural beauty for her special day.",
                            Name = "Bridal Makeup",
                            Price = 1500
                        },
                        new
                        {
                            Id = 2,
                            Desc = "Bold and glamorous makeup for parties and social events.",
                            ImageUrl = "makeUp1.jpg",
                            Name = "Party Glam",
                            Price = 800
                        },
                        new
                        {
                            Id = 3,
                            Desc = "A subtle and fresh makeup style for everyday wear.",
                            Name = "Natural Look",
                            Price = 500
                        },
                        new
                        {
                            Id = 4,
                            Desc = "Sophisticated makeup perfect for evening events and dinners.",
                            Name = "Evening Elegance",
                            Price = 1000
                        },
                        new
                        {
                            Id = 5,
                            Desc = "Shimmery and radiant makeup for a glamorous, standout look.",
                            Name = "Glamour Shine",
                            Price = 1200
                        },
                        new
                        {
                            Id = 6,
                            Desc = "Vibrant and creative makeup for festivals and fun events.",
                            Name = "Festival Glam",
                            Price = 700
                        },
                        new
                        {
                            Id = 7,
                            Desc = "Radiant and glowing makeup designed for brides who want a luminous look.",
                            Name = "Bridal Glow",
                            Price = 1600
                        },
                        new
                        {
                            Id = 8,
                            Desc = "Elegant makeup for special events like anniversaries and galas.",
                            Name = "Special Occasion",
                            Price = 1300
                        },
                        new
                        {
                            Id = 9,
                            Desc = "High-fashion makeup inspired by the looks of celebrities and runway models.",
                            Name = "Celebrity Look",
                            Price = 2000
                        },
                        new
                        {
                            Id = 10,
                            Desc = "Refined and minimalist makeup for a naturally elegant look.",
                            Name = "Simple Elegance",
                            Price = 600
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("desc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 2,
                            Location = "Cairo",
                            Name = "Basic Photography Package",
                            Price = 3000.0,
                            Type = "Photography"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 3,
                            Location = "Alexandria",
                            Name = "Videography Session",
                            Price = 4000.0,
                            Type = "Videography"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 4,
                            Location = "Giza",
                            Name = "Engagement Photography",
                            Price = 3500.0,
                            Type = "Engagement Shoot"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 5,
                            Location = "Sharm El Sheikh",
                            Name = "Pre-Wedding Photoshoot",
                            Price = 4500.0,
                            Type = "Pre-Wedding Shoot"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 6,
                            Location = "Luxor",
                            Name = "Wedding Day Coverage",
                            Price = 8000.0,
                            Type = "Wedding Photography"
                        },
                        new
                        {
                            Id = 6,
                            Duration = 2,
                            Location = "New Cairo",
                            Name = "Couple Photography",
                            Price = 2500.0,
                            Type = "Couple Shoot"
                        },
                        new
                        {
                            Id = 7,
                            Duration = 3,
                            Location = "Tanta",
                            Name = "Bridal Portrait Session",
                            Price = 3000.0,
                            Type = "Bridal Portraits"
                        },
                        new
                        {
                            Id = 8,
                            Duration = 4,
                            Location = "Mansoura",
                            Name = "Fashion Photo Session",
                            Price = 5000.0,
                            Type = "Fashion Photography"
                        },
                        new
                        {
                            Id = 9,
                            Duration = 5,
                            Location = "Hurghada",
                            Name = "Event Videography & Photography",
                            Price = 6000.0,
                            Type = "Event Coverage"
                        },
                        new
                        {
                            Id = 10,
                            Duration = 3,
                            Location = "Port Said",
                            Name = "Family Photography",
                            Price = 3500.0,
                            Type = "Family Shoot"
                        });
                });

            modelBuilder.Entity("MVC_Projec2.Models.SessionImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "session1.jpg",
                            SessionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "session2.jpg",
                            SessionId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "session3.jpg",
                            SessionId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "session4.jpg",
                            SessionId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "session5.jpg",
                            SessionId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "session6.jpg",
                            SessionId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "session7.jpg",
                            SessionId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "session8.jpg",
                            SessionId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "session9.jpg",
                            SessionId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "session10.jpg",
                            SessionId = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "915f09d1-f412-4330-b6cf-858d7657b54d",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "20825a0f-7b3e-46b6-8880-271eac074c8e",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MVC_Projec2.Models.AtelierImages", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Atelier", "Atelier")
                        .WithMany("Images")
                        .HasForeignKey("AtelierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atelier");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Booking", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Atelier", "Atelier")
                        .WithMany()
                        .HasForeignKey("Atelier_Id");

                    b.HasOne("MVC_Projec2.Models.Decor", "Decor")
                        .WithMany()
                        .HasForeignKey("Decor_Id");

                    b.HasOne("MVC_Projec2.Models.Hall", "Hall")
                        .WithMany()
                        .HasForeignKey("Hall_Id");

                    b.HasOne("MVC_Projec2.Models.MakeUp_Service", "MakeUp")
                        .WithMany()
                        .HasForeignKey("MakeupId");

                    b.HasOne("MVC_Projec2.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("Session_Id");

                    b.HasOne("MVC_Projec2.Models.ApplicationUser", "user")
                        .WithMany("Bookings")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atelier");

                    b.Navigation("Decor");

                    b.Navigation("Hall");

                    b.Navigation("MakeUp");

                    b.Navigation("Session");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Comment", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_Projec2.Models.DecoreImage", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Decor", "Decor")
                        .WithMany("Images")
                        .HasForeignKey("DecorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decor");
                });

            modelBuilder.Entity("MVC_Projec2.Models.HallImage", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Hall", "Hall")
                        .WithMany("Images")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("MVC_Projec2.Models.MakeUpImages", b =>
                {
                    b.HasOne("MVC_Projec2.Models.MakeUp_Service", "makeUp")
                        .WithMany("Images")
                        .HasForeignKey("MakeUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("makeUp");
                });

            modelBuilder.Entity("MVC_Projec2.Models.SessionImages", b =>
                {
                    b.HasOne("MVC_Projec2.Models.Session", "Session")
                        .WithMany("Images")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Projec2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MVC_Projec2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVC_Projec2.Models.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Atelier", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Decor", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Hall", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MVC_Projec2.Models.MakeUp_Service", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("MVC_Projec2.Models.Session", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
